# Generated by Django 3.2.5 on 2021-12-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shartnomaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField()),
                ('tolov_oyi', models.CharField(max_length=20)),
                ('chegirma_status', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=10)),
                ('ch_sababi', models.CharField(max_length=50)),
                ('ch_miqdori', models.PositiveBigIntegerField()),
                ('t_sanasi', models.DateField()),
                ('kassir', models.CharField(max_length=30)),
                ('tolashi_lozim', models.PositiveBigIntegerField()),
                ('naqd', models.PositiveBigIntegerField()),
                ('bank', models.PositiveBigIntegerField()),
                ('plastik', models.PositiveBigIntegerField()),
                ('click', models.PositiveBigIntegerField()),
                ('jami_tolandi', models.PositiveBigIntegerField()),
                ('jami_qoldi', models.PositiveBigIntegerField()),
                ('shartnoma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shartnomaApp.shartnoma')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shartnomaApp.student')),
                ('ustoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shartnomaApp.ustoz')),
            ],
        ),
    ]
